# Site
repository: maxbbender/resume
favicon: images/linux-logo.webp

# Personal info
name: Max Bender
title: CICD Architect and Principal Engineer
email: maxbbender@gmail.com
website: www.github.com/maxbbender/resume

# Social links
# twitter_username: facespics
github_username:  maxbbender
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: max-bender-a3035198
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Max Bender and titles are weird, but if I were to give myself one it would be a Jr. Principal Engineer? While listening to a random episode of [Arrested DevOps](https://www.arresteddevops.com/) with [Silvia Botros](https://www.linkedin.com/in/silviabotros/) I heard this title that I had never heard before, a "Principal Engineer". She explores it more [in her blog post](https://blog.dbsmasher.com/2019/01/28/on-being-a-principal-engineer.html) but the short of it is
  
  *"[being a Principal Engineer] is far more strategic, it's far more business oriented, it's involving a lot more influence, being an influencer without having the management title."*

  *"[during the time becoming a Principal Engineer you] need to be a force multiplier. There was a clear transition from me writing code to teaching others how to write code that's actually clean and doesn't cause us trouble too fast down the line. One of the big parts of Principal Engineering in my mind is you teach more than you actually do yourself."*

  Why I call myself just a Jr. Principal Engineer is because there are a lot attributes of what Silvia talks about that I was already doing in my day to day job, but not quite at the same scale. I have a lot of experience to gain in being an influencer, but at IBM I feel like I fit the role of the *force multiplier* pretty well.

  Primarily, my work has been on CICD and DevOps solutions, but I often get this itch to create something new. <mark>Python</mark> is my go-to scripting language but I'm not afraid of a little <mark>Bash</mark> or <mark>Ruby</mark> if the use-case calls for it or I am trying to work with a library that requires the aforementioned (i.e <mark>Chef</mark>). The instant gratification of making websites and working with complex relational database setups is a puzzle that I relish. Using <mark>Flask</mark> and <mark>SQLAlchemy</mark> I have put together websites as a consultant on the side. See the NexNest project as an example.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in DevOps and Software Development some of my other interests and hobbies are:
   - Cooking
   - Competitive Gaming
   - Playing with my pupper Zoey

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
